apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcd-project-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-8
    template:
      metadata:
        labels:
          app: project-8
      spec:
        containers:
        - name: project-8
          image: rakinkhan/project-8:latest
  
